# Generated by Django 3.2.18 on 2023-03-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Received', 'Received'), ('Processing', 'Processing'), ('Dispatched', 'Dispatched'), ('On Hold', 'On Hold'), ('Cancelled - Refund Pending', 'Cancelled - Refund Pending'), ('Cancelled', 'Cancelled'), ('Returned - Refund Pending', 'Returned - Refund Pending'), ('Returned', 'Returned')], default='Received', max_length=254),
        ),
    ]
