# Generated by Django 3.2.18 on 2023-04-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_size',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='color_box',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='size_box',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
