# Generated by Django 3.2.18 on 2023-04-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20230407_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='color_box',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='size_box',
            new_name='size',
        ),
    ]
