# Generated by Django 3.2.18 on 2023-04-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20230408_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Received', 'Received'), ('Processing', 'Processing'), ('Dispatched', 'Dispatched'), ('On Hold', 'On Hold'), ('Cancelled - Refund Pending', 'Cancelled - Refund Pending'), ('Cancelled', 'Cancelled'), ('Returned - Refund Pending', 'Returned - Refund Pending'), ('Returned', 'Returned')], default='Received', max_length=254, null=True),
        ),
    ]
