# Generated by Django 3.2.18 on 2023-03-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productvariant_discounted_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagevariant',
            old_name='alt',
            new_name='image_variant_alt',
        ),
        migrations.AddField(
            model_name='imagevariant',
            name='image_variant_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='imagevariant',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
