# Generated by Django 3.2.18 on 2023-03-23 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20230323_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagevariant',
            name='image_variant_url',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='title',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variant', to='products.product'),
        ),
    ]
