# Generated by Django 3.2.18 on 2023-03-27 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20230327_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVariant',
            new_name='Variant',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='variant',
            new_name='variant_options',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
